services:
  - type: web
    name: solrealm-server
    env: node
    region: frankfurt
    buildCommand: npm install && npm run server-build
    startCommand: npm run server-start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
